[build-system]
  build-backend = "uv_build"
  requires = ["uv_build"]

[dependency-groups]
  dev = [
    "dycw-utilities>=0.176.6, <1",
    "orjson>=3.11.5, <4",
    "pyright",
    "rich>=14.2.0, <15",
    "dycw-utilities[test]",
    "rich",
  ]

[project]
  dependencies = [
    "click>=8.3.1, <9",
    "dycw-utilities>=0.177.0, <1",
    "inflect>=7.5.0, <8",
    "libcst>=1.8.6, <2",
    "packaging>=25.0, <26",
    "pydantic>=2.12.5, <3",
    "pyyaml>=6.0.3, <7",
    "rich>=14.2.0, <15",
    "ruamel-yaml>=0.19.0, <1",
    "tomlkit>=0.13.3, <1",
    "typed-settings[attrs,click]>=25.3.0, <26",
    "xdg-base-dirs>=6.0.2, <7",
  ]
  description = "Library of actions"
  name = "dycw-actions"
  readme = "README.md"
  requires-python = ">= 3.12"
  version = "0.6.22"

  [project.scripts]
    action = "actions.cli:_main"

[tool]
  [tool.uv]
    [tool.uv.build-backend]
      module-name = "actions"
      module-root = "src"
